### ISSUE TITLE
No writes to database until switched to Native Mode

### ISSUE THREAD

**Issue by fulv** [firebase/codelab-friendlychat-web#519] opened 2020-05-06 19:56 UTC
### [REQUIRED] Codelab info

https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#7

### [REQUIRED] Project setup

`cloud-functions-start`

### [REQUIRED] Describe the problem

The codelab app does not write to the database until it is upgraded to Native mode.
When I deploy and run the app as in step 4, any messages typed into the chat window are not persisted.
Going to https://console.firebase.google.com/u/0/project/myapp-abcd/database, I see the warning:

> This project is set up to use Cloud Firestore in Datastore mode. This mode can only be accessed from Google Cloud Platform
> **Go to Cloud Plaform** (https://console.cloud.google.com/datastore?project=myapp-abcd&authuser=0)
> 

and if I go to Cloud Platform, I see:

> Since your database is empty, you can still switch to Cloud Firestore in Native mode to get more features.
> **Learn More**  |  **Switch to Native Mode**

When I click on "Switch to Native Mode", the messages are stored and then finally the database content is shown at https://console.firebase.google.com/u/0/project/myapp-abcd/database

###  Suggested fix

As a firebase and firestore etc n00bie, this is all unclear to me.  If having Firestore in Native mode is mandatory to make the codelab work, then it would be good to just instantiate it in Native mode from the get go, without making me switch manually since I don't really know what that means.
If it is not mandatory, then something is missing in the codelab to make it work.

**Comment by samtstern** [comment] 2020-05-07 16:48
@fulv thanks for reporting this in detail.  There seems to be something going on with the Firebase console where some users are getting stuck in Firestore Datastore Mode when they want to be in Native mode.   I am working with the Firebase console team to figure out why that's the case.

Because this is not specific to this codelab and Native mode should be the default I am going to close this issue.  If I get an update from the console team I will post it.

**Closed by samtstern** 2020-05-07 16:48 UTC
Labels: codelab

**Comment by fulv** [comment] 2020-05-07 17:59
@samtstern that's true, it's not specific to this codelab.  It's just easy to get lost in the forest of firebase trees.

**Comment by samtstern** [comment] 2020-05-07 20:44
Yeah I agree, these types of paper cuts are really important!  We’ve actually been digging into this one all day, hoping we find the root cause soon.
